import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { CssBaseline } from "@mui/material";
import ThemeProviderClient from "../lib/providers/colorThemeProvider";
import Navbar from "../myComponents/navbar";
import { AuthProvider } from "@/lib/providers/authenticationProvider";
import { cookies } from "next/headers";
import { readDB } from "@/server/db";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "@/lib/providers/queryProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token")?.value;

  let initialUser = null;
 //hna ba2a what makes seesion persistent across refreshes and tabs
  if (token?.startsWith("fawaz-token-")) {
    const userId = Number(token.replace("fawaz-token-", ""));
    if (Number.isFinite(userId)) {
      const db = await readDB();
      const user = db.users.find((u) => u.id === userId);
      if (user) {
        initialUser = { id: user.id, email: user.email, name: user.name };
      }
    }
  }

  return (
    <html lang="en">
      <body>
        {/* <ClientProvider> 
        In app/layout.tsx you should wrap the entire app with:
           React Query Provider
        MUI ThemeProvider
          ssBaselin
          Your Snackbar provider/store listener
Dark mode state context
        */}
        {/* MUI cache provider – required for proper SSR/streaming 
        When you use:
Next.js App Router (app/ folder)
Server Components + streaming
Material UI (MUI)
You can get problems like:
styles flashing or disappearing
styles loading in the wrong order
hydration warnings
duplicated CSS
That’s because:
MUI uses Emotion to generate CSS at runtime
Next App Router streams HTML in chunks
Without coordination, CSS can be injected too late or twice
 AppRouterCacheProvider fixes that.     
        */}
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {/* Client-side theme el ana 3amlo  */}
          <ThemeProviderClient>
            <QueryProvider>
              <AuthProvider initialUser={initialUser}>
                <CssBaseline />

                <Navbar />
                <div className="pt-27">{children}</div>
              </AuthProvider>
            </QueryProvider>
          </ThemeProviderClient>
        </AppRouterCacheProvider>

        {/* </ClientProvider> */}
        {/* <ToastProvider /> */}
      </body>
    </html>
  );
}
